### ISSUE TITLE
ブラウザ：アイテム購入画面が開けない

### ISSUE THREAD

**Issue by andanteyk** [andanteyk/ElectronicObserver#93]
アイテムを購入しようとすると、購入確認画面が開かずそのまま閉じる

**Comment by RadarNyan** [comment]
This is because the current PageScript hides everything other than ```#game_frame```

```css
div #block_background { visibility: visible; width: 100%; height: 100%; }
div #alert { visibility: visible; overflow: scroll; top: 0; left: 3%; height: 100%; width: 90%; padding:2%;}
```
Giving those two elements extra styles like this should fix it.
